apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-v2
  labels:
    app: webapp
    version: "2.0"
  annotations:
    contact: "devops-team@example.com"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
      version: "2.0"
  template:
    metadata:
      labels:
        app: webapp
        version: "2.0"
      annotations:
        description: "Second release of the web application with new features"
    spec:
      containers:
      - name: webapp
        image: nginx:1.18
        ports:
        - containerPort: 80

