apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-v1
  labels:
    app: webapp
    version: "1.0"
  annotations:
    contact: "devops-team@example.com"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
      version: "1.0"
  template:
    metadata:
      labels:
        app: webapp
        version: "1.0"
      annotations:
        description: "Initial release of the web application"
    spec:
      containers:
      - name: webapp
        image: nginx:1.14
        ports:
        - containerPort: 80

